[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "f1tenth_gym"
version = "1.0.0dev"
description = "Gym environment for F1TENTH"
license = "MIT"
authors = [
  { name = "Hongrui Zheng" },
  { name = "Renukanandan Tumu" },
  { name = "Luigi Berducci" },
  { name = "Ahmad Amine" },
  { name = "Joseph Auckley" },
  { name = "Matthew O'Kelly" },
  { name = "Aman Sinha" }
]
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
    "gymnasium>=0.29.1,<0.30",
    "numpy>=1.18",
    "pillow>=9.0.1",
    "scipy>=1.7.3",
    "numba>=0.55.2",
    "pyyaml>=5.3.1",
    "pyopengl==3.1.9",
    "opencv-python",
    "yamldataclassconfig",
    "requests>=2.31.0",
    "pyqtgraph>=0.13.7",
    "PyQt6>=6.9.1",
    "pandas>=2.3.0",
    "PyOpenGL-accelerate==3.1.9",
]

[tool.pixi.dependencies]
python = ">=3.9,<3.12"
pytest = ">=7.4.4"

[build-dependencies]
# Needed for PyOpenGL-accelerate if user insists on building it
c-compiler = "*"
cython = "*"

[tasks]
test = "pytest -ra"
format = "black f1tenth_gym"
lint = "flake8 f1tenth_gym"
isort = "isort f1tenth_gym"

[tool.pixi.pypi-dependencies]
f1tenth_gym = { path = ".", editable = true }

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests", "integration"]

[tool.setuptools]
packages = ["f1tenth_gym"]

[tool.setuptools.package-data]
f1tenth_gym = ["**/*"]